Lippy loves arch

diff --git a/bin/sbuild b/bin/sbuild
--- a/bin/sbuild
+++ b/bin/sbuild
@@ -4,7 +4,7 @@ set -e
 
 script_name=`basename "$0"`
 container_name="swarmbot"
-cores="4"
+cores="6"
 cmake_type="Debug"
 user="$(id --user --name)"
 env_file="~/.config/swarmfarm/swarmbot_build_env"
@@ -24,15 +24,17 @@ function print_help {
     echo "Arguments"
     echo ""
     echo " What to build"
-    echo "   -p | --package {PACKAGE}       the package to build - appended to catkin_make as '--pkg {PACKAGE}'. Default builds everything"
-    echo "   -o | --only-package {PACKAGE}  the package to build in isolation. Uses CATKIN_WHITELIST_PACKAGES to skip all deps. Default builds everything"
-    echo "   -t | --tests                   whether to build tests"
+    echo "   -p | --package {PACKAGE}                    the package to build - appended to catkin_make as '--pkg {PACKAGE}'. Default builds everything"
+    echo "   -o | --only {PACKAGE[,PACKAGE](:FILE.cpp)}  build a single package or file in isolation"
+    echo "                                               For packages specify a package name or multiple, with , seperation. Uses CATKIN_WHITELIST_PACKAGES to skip all deps"
+    echo "                                               For a single file - do package then filename in src dir with : inbetween. Does not work with other build options"
+    echo "   -t | --tests                                whether to build tests"
     echo "        --debug | --release "
     echo "        --cmake-type {TYPE} "
-    echo "                                  the CMAKE_BUILD_TYPE. Defaults to Debug"
+    echo "                                         the CMAKE_BUILD_TYPE. Defaults to Debug"
     echo ""
     echo " How to build it"
-    echo "   -c | --cores {CORES}           the amount of cores to use. Defaults to 4, and ups to 16 automatically if --dist is specified"
+    echo "   -c | --cores {CORES}           the amount of cores to use. Defaults to 6, and ups to 16 automatically if --dist is specified"
     echo "   -d | --dist                    use a distributed build. This is hardcoded around the Bendee distcc config"
     echo "   -h | --hosts {HOSTS}           the distcc hosts to use. Defaults to the bendee standard. This argument requires newline seperation ala the hosts config file for distcc"
     echo "   -e | --env-file {FILE}         an environment file to source before building. This can be a systemd EnvironmentFile or a bash file"
@@ -163,17 +165,25 @@ case $key in
             exit 1
         fi
         ;;
-    -o|--only-package)
+    -o|--only)
         if [ -z "$package_name" ]; then
             shift
-            package_name="$1"
-            package_arg="-DCATKIN_WHITELIST_PACKAGES=$package_name"
+            if echo "$1" | grep -q -e ","; then
+                package_name="$(echo "$1" | sed 's/,/;/g')"
+                package_arg="-DCATKIN_WHITELIST_PACKAGES='$package_name'"
+            elif echo "$1" | grep -q -e ":"; then
+                package_name="$(echo $1 | cut -d ':' -f 1)"
+                file_name="$(echo $1 | cut -d ':' -f 2)"
+            else
+                package_name="$1"
+                package_arg="-DCATKIN_WHITELIST_PACKAGES=$package_name"
+            fi 
             shift
         else 
             >&2 echo "Can't specify $1 more than once - see $script_name --help"
             exit 1
         fi
-        ;;        
+        ;;    
     -t|--tests)
         if [ -z "$test_target" ]; then
             shift
@@ -255,7 +265,22 @@ fi
 
 catkin_command="catkin_make ${no_colour} ${package_arg} -j${cores} -DCMAKE_BUILD_TYPE=${cmake_type} ${test_target}"
 
+if [ -n "$file_name" ]; then 
+    file_src="$HOME/swarmbot4/swarmbot_ws/src/${package_name}/src/${file_name}" 
+    file_any="$HOME/swarmbot4/swarmbot_ws/src/${package_name}/${file_name}"
+
+    if [ -f $file_src ]; then
+        catkin_command="make -f build/${package_name}/Makefile src/${file_name}.o"
+    elif [ -f $file_any ]; then
+        catkin_command="make -f build/${package_name}/Makefile ${file_name}.o"
+    else 
+        >&2 echo "Can't find file with path ${file_src} or ${file_any}"
+        exit 1
+    fi
+fi
+
 final_command="${source_command}; ${cd_command}; ${set_distcc_file}; ${set_c_and_cxx_compiler}; ${set_ccache_prefix}; ${catkin_command}"
+
 
 if [ -z "$do_dryrun" ]; then 
     if [ -n "$less_cmd" ]; then 
